### ISSUE TITLE
Package still maintained?

### ISSUE THREAD

**Issue by dandv** [SimonDegraeve/meteor-jade-handlebars#29]
This package seems no longer maintained. If that is the case, you can hide it from Atmosphere searches while letting dependent packages and apps use it with the following command:

```
meteor admin set-unmigrated <package:name>
```

To remove `mrt` as a contributor:
    meteor admin maintainers yourusername:your-package --remove mrt

If you were originally the maintainer on the old package system, you can attach your Meteor Developer account at http://atmosphere.meteor.com/accounts, then ping @tmeasday to give you ownership of the old package.

**Comment by SimonDegraeve** [comment]
Indeed it is no longer maintained. I just updates the readme. 
Unfortunately, I cannot connect to `Atmosphere v1 Accounts` (cannot remember credentials). I am willing to delete this package from the search engine, but didn't figure out how. 

Any idea @tmeasday?

**Comment by tmeasday** [comment]
Thanks @SimonDegraeve I've gone ahead and just done it for you. Are there other packages which you would like to claim?

**Comment by SimonDegraeve** [comment]
Nope, no other packages. Thanks.
